services:
  web:
    build:
      context: .
    container_name: web
    command: bin/dev #bundle exec rails s -b '0.0.0.0' -p 3000
    ports:
      - 3000:3000
    volumes: &web-volumes
      - .:/rails_app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - bundle_cache:/bundle_cache

    environment: &web-environment
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3000
      RUBYOPT: -W:no-deprecated -W:no-experimental
      REDIS_URL: redis://redis:6379/1

    depends_on:
      - db
      - sidekiq
      - redis

  db:
    image: postgres:15.4
    container_name: db
    hostname: db
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

  sidekiq:
    build:
      context: .
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment: *web-environment
    volumes: *web-volumes
    depends_on:
      - redis
      - db

volumes:
  bundle_cache:
  postgres_data:
  redis_data:
