version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine

  sidekiq:
    build: .
    command: ["bundle", "exec", "sidekiq"]
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
      - REDIS_URL=redis://redis:6379

  web:
    build: .
    command: ["rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app:cached

    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    entrypoint: ./entrypoint.sh

volumes:
  db-data:
